### ISSUE TITLE
[세미나 제안] 해외 기업 코딩인터뷰에 관심 있으신분 계실까요?

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/AcademicConference#123]
### Discussed in https://github.com/ThinkAboutSoftware/AcademicConference/discussions/116

<div type='discussions-op-text'>

<sup>Originally posted by **wooyaggo86** January 25, 2022</sup>
안녕하세요.지난주 GDG와 F-lab이라는 곳을 통해서 코딩인터뷰 관련된 주제로 몇 가지 팁을 이야기할 기회가 있었는데요.
학술회의에서도 관심 있으신분들이 계시면, 여기에서도 나눔하고 싶어 글 올립니다.
괜찮으시다면 다음주(독서모임이 없는 주) 금요일(2월 4일)로 생각하고 있어요.
발표시간은 1시간 정도가 될 것 같고, 발표자료는 아래 링크에서 보실 수 있습니다.
관심있으시면 댓글 부탁드립니다~

https://github.com/wooyaggo86/Presentation/blob/main/20210123/(%EB%82%98%EB%A7%8C%20%EB%AA%B0%EB%9E%90%EB%8D%98)%20FFANG%20%EC%BD%94%EB%94%A9%20%EC%9D%B8%ED%84%B0%EB%B7%B0%EC%9D%98%20%EB%B9%84%EB%B0%80.md?plain=1</div>

**Comment by Joseph-Cha** [comment]
엇 이거 우현님 깃헙 몰래 눈팅하다가 본 리포지군요,,?ㅋㅋㅋ
FAANG에 들어가려면 저 정도는 해야하는구나 하면서 속으로 혀를 내둘렀던..
무튼 저는 참석 희망합니다!
