### ISSUE TITLE
<프로그래밍 심리학> 1부 인간 행위로 보는 프로그래밍, 총 75 페이지, 2024-01-12

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/AcademicConference#338]
### (최대한) 1월 11일 목요일 까지

- 프로그래밍 심리학, 1부 인간 행위로 보는 프로그래밍
  - (Required) 1장 프로그램 읽기
  - (Required) 2장 좋은 프로그램이란 무엇인가?
  - (Required) 3장 프로그래밍이란 행위를 연구할 방법은 무엇인가?
- 해당 주차의 챕터 부분을 읽고 리뷰 내용을 자유 서식으로 pull request 생성
- (Required) 1부, 1장 ~ 3장에서 각 챕터 당 최소 1개 이상 논의 내용 작성, 총 3개
- (Optional) 책 내용 정리 외에 추가 논의, 질문, 공유 정보 작성
- Reviewer는 자신을 제외한 멤버 7명 할당 (Assignees 멤버 목록 확인)
- 정해진 날짜에 맞춰서 과제 제출하는 식 보다는 먼저 다 읽었다면 pull request를 빠르게 요청하는 것도 좋음

### 1월 12일 금요일 22:59 까지

다른 멤버 7명의 pull request review를 진행 

- 다른 멤버들의 pull request 적어도 1개 이상 코멘트 추가, 이후 approve 체크를 통해 리뷰 했다는 걸 인증 (github code review 방식과 동일합니다)
- 멤버가 총 8명이므로 자신을 제외한 멤버의 pull request review를 7회 진행해야 합니다

### 1월 12일 금요일 23:00

- Google meet를 통한 온라인 미팅으로 리뷰 진행
- 구글 캘린더 일정에 google meet 링크가 포함되어 있습니다.
- https://meet.google.com/wri-aaif-hhc

### Presentation Order (Updated asynchronous real time)

pull request 늦게 올린 순서대로 한 챕터씩 돌아가면서 진행
멤버가 총 8명이고, 챕터 3개를 진행하므로 챕터 하나 당 두명씩 논의를 진행하고 남은 두 사람은 남은 챕터 중에 진행하고 싶은 챕터를 결정해서 진행

**Comment by yeslee-v** [comment]
날짜를 헷갈려서 오늘까지인줄 알았네요;; 일단 PR은 올리겠습니다ㅠㅠ
