### ISSUE TITLE
[Maintenance] 우현님 프로그래밍 심리학 1부 정리내용 폴더 생성 필요

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/AcademicConference#353]
우현님의 프로그래밍 심리학 정리 내용이 github id 폴더로 되어 있지 않아서 폴더 생성 후 파일 이동 해야 함

@wooyaggo86 님이 해주실 수 있으면 해주시고
이번 주 까지 (1월 20일) 만약 못보시거나 해서 안되어 있으면 제가 해 놓겠습니다.

<img width="220" alt="image" src="https://github.com/ThinkAboutSoftware/AcademicConference/assets/17442457/bd90fbdd-dc37-4824-be8f-a7585d535a8a">

해당 내용에 대해 pull request를 주시면 required reviewer에 상관 없이 승인하고 바로 merge 할 예정입니다.

**Comment by wooyaggo86** [comment]
헛.. 아이디를 깜박했네요. PR #357 요청드렸습니다
